// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Athlete struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Grade          int64  `json:"grade"`
	PersonalRecord string `json:"personalRecord"`
	Events         string `json:"events"`
}

type Meet struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Date        string `json:"date"`
	Location    string `json:"location"`
	Description string `json:"description"`
}

type Result struct {
	ID        int64  `json:"id"`
	AthleteID int64  `json:"athleteId"`
	MeetID    int64  `json:"meetId"`
	Time      string `json:"time"`
	Place     int64  `json:"place"`
}
