// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createResult = `-- name: CreateResult :one
INSERT INTO results (athlete_id, meet_id, time, place)
VALUES (?, ?, ?, ?)
RETURNING id, athlete_id, meet_id, time, place
`

type CreateResultParams struct {
	AthleteID int64  `json:"athleteId"`
	MeetID    int64  `json:"meetId"`
	Time      string `json:"time"`
	Place     int64  `json:"place"`
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (Result, error) {
	row := q.db.QueryRowContext(ctx, createResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
	)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.MeetID,
		&i.Time,
		&i.Place,
	)
	return i, err
}

const getAllAthletes = `-- name: GetAllAthletes :many
SELECT id, name, grade, personal_record, events FROM athletes ORDER BY name
`

func (q *Queries) GetAllAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getAllAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMeets = `-- name: GetAllMeets :many
SELECT id, name, date, location, description FROM meets ORDER BY date
`

func (q *Queries) GetAllMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, personal_record, events FROM athletes WHERE id = ?
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int64) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
	)
	return i, err
}

const getResultsByMeet = `-- name: GetResultsByMeet :many
SELECT r.id, r.athlete_id, r.meet_id, r.time, r.place, a.name AS athlete_name
FROM results r
JOIN athletes a ON r.athlete_id = a.id
WHERE r.meet_id = ?
ORDER BY r.place
`

type GetResultsByMeetRow struct {
	ID          int64  `json:"id"`
	AthleteID   int64  `json:"athleteId"`
	MeetID      int64  `json:"meetId"`
	Time        string `json:"time"`
	Place       int64  `json:"place"`
	AthleteName string `json:"athleteName"`
}

func (q *Queries) GetResultsByMeet(ctx context.Context, meetID int64) ([]GetResultsByMeetRow, error) {
	rows, err := q.db.QueryContext(ctx, getResultsByMeet, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResultsByMeetRow
	for rows.Next() {
		var i GetResultsByMeetRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Time,
			&i.Place,
			&i.AthleteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTimes = `-- name: GetTopTimes :many
SELECT r.id, r.time, r.place, a.name AS athlete_name, m.name AS meet_name
FROM results r
JOIN athletes a ON r.athlete_id = a.id
JOIN meets m ON r.meet_id = m.id
ORDER BY r.time ASC
LIMIT 10
`

type GetTopTimesRow struct {
	ID          int64  `json:"id"`
	Time        string `json:"time"`
	Place       int64  `json:"place"`
	AthleteName string `json:"athleteName"`
	MeetName    string `json:"meetName"`
}

func (q *Queries) GetTopTimes(ctx context.Context) ([]GetTopTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTimesRow
	for rows.Next() {
		var i GetTopTimesRow
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Place,
			&i.AthleteName,
			&i.MeetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
